---

- name: Create a instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: jameel_nv
    instance_type: t2.micro
    security_group: sg-40502925
    image: ami-d05e75b8
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         instance_tags: {"Name":"Ellucian-ROR"}
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-29aa575e
         assign_public_ip: yes
      register: ec2
    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: Configure instance(s)
  hosts: launched
  sudo: yes
  remote_user: ubuntu
  gather_facts: True
  roles:
    - ror